# Generated by Django 4.2.14 on 2024-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='review_interval_box',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Again'), (1, 'Tomorrow'), (2, '2 days'), (3, '4 days'), (4, '1 week'), (6, '2 weeks'), (7, '1 month')], default=0),
        ),
    ]
